<?php

namespace InvoicesBundle\Repository;

/**
 * InvoiceDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceDataRepository extends \Doctrine\ORM\EntityRepository
{
}
